//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Article
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string PhotoPath { get; set; }
        public int PublisherID { get; set; }
        public int NewsPaperID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual ArticleCategory ArticleCategory { get; set; }
        public virtual NewsPaper NewsPaper { get; set; }
    }
}
