//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Rating
    {
        public int ID { get; set; }
        public double Rating1 { get; set; }
        public int RatingsGiven { get; set; }
        public int NewsPaperID { get; set; }
    
        public virtual NewsPaper NewsPaper { get; set; }
    }
}
